### ISSUE TITLE
Adding a Timeout if the Serial Port does not respond

### ISSUE THREAD

**Issue by joesan** [jodersky/akka-serial#41]
Could this be added to the implementation? I would need a Timeout message after writing bytes to the opened serial port where I can specify after a certain FiniteDuration, the read should Timeout? I have a scenario where I have two devices and I try to connect to these two devices one after the other. If the first one does not respond after a certain time (which I currently have in my Actor), I try the next one. Could this be added to the IO(Serial) actor such that it handles this internally in the library itself, rather than me controlling it from outside?

I can post you an example tomorrow.

**Comment by jodersky** [comment]
Could you elaborate on the protocol in this case, i.e. what messages should the serial manager send back to the client when a timeout occurs?

It seems to me that this can easily be implemented in client code, when required:

1. schedule a timeout message when opening the connection
2. when the message arrives do one of the following
    - if no data has arrived, handle the timeout scenario
    - else ignore the timeout

I'm reluctant to include this into the project since it adds extra complexity and I don't think this timeout feature is required by most use-cases
