### ISSUE TITLE
java.lang.NoSuchMethodError on Java 8

### ISSUE THREAD

**Issue by sirthias** [jodersky/akka-serial#48]
Release `4.2.0` is broken on Java 8, it fails with this error:

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
 	at akka.serial.SerialOperator$Reader$.loop(SerialOperator.scala:25)
 	at akka.serial.SerialOperator$Reader$.run(SerialOperator.scala:43)
```

The reason is a breaking change in Java 9+ that `akka-serial` `4.2.0` was built on.
The problem is described nicely here: https://jira.mongodb.org/browse/JAVA-2559

Other projects have (had) the same problem, e.g. `lmdbjava`:
https://github.com/lmdbjava/lmdbjava/issues/117

**Comment by jodersky** [comment]
IIRC the last release (was done manually (on JDK 11) because CI was down. I thought that the [target flags in the build](https://github.com/jodersky/akka-serial/blob/master/build.sbt#L12) would be sufficient for ensuring backwards compatibly, but it seams that I am mistaken. I think a new release with Java 8 should fix this.

**Comment by sirthias** [comment]
Yes, you can either build the release on Java 8 or apply https://github.com/jodersky/akka-serial/pull/49. Doing both is probably best... ;-)
